[workspace]
default-members = [ "example" ]
members = [ "crates/koruma", "crates/koruma-core", "crates/koruma-derive", "example" ]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/stayhydated/koruma"
rust-version = "1.88"
version = "0.1.0"

[workspace.dependencies]
bon = "3.8.1"
derive-getters = "0.5.0"
es-fluent = "0.4.2"
heck = "0.5.0"
insta = "1.45.1"
koruma = { path = "crates/koruma", version = "0.1.0" }
koruma-core = { path = "crates/koruma-core", version = "0.1.0" }
koruma-derive = { path = "crates/koruma-derive", version = "0.1.0" }
paste = "1.0.15"
prettyplease = "0.2.37"
proc-macro-error2 = "2.0"
proc-macro2 = "1.0.92"
quote = "1.0.38"
syn = "2.0.112"
