[package]
name = "koruma-collection-example"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license = "Unlicense"
publish = false

[dependencies]
koruma-collection = { features = [ "tui", "fluent" ], workspace = true }
