[package]
name = "koruma"
description = """
The koruma crate
"""
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
readme = "README.md"

[features]
default = [ "derive" ]
derive = [ "koruma-derive" ]

[dependencies]
bon = { workspace = true }
koruma-core = { workspace = true }
koruma-derive = { optional = true, workspace = true }
